### PR TITLE
Add circle & point labeling, and 4th canvas layer

### PR DESCRIPTION
**Pull request by RF5**
These commits add the circle and point label types to work with the latest changes on master. Circle type shows user where circle will be placed and allows resizing before placement with either the + and - keys on the numpad (fine control), or with Shift+scroll on the mouse (course control). 

The point label type is functionally the same as the previous pull request, but is more in line with the refactor changes implemented in master. Everything should be in line with how you have organized different types of labels on master.

4th canvas layer ("canvas-live") was added to show previews of user action before they do it. Currently only has a function in the circle label mode, where it renders a preview circle in the canvas-live over the rest of the canvas layers before the user places the circle (to allow them to see the effects of their placement). It does not change any configuration/functioning of the existing layers.

### CODE REVIEW

**Comment by shaunirwin** [comment]
The functionality looks good. I like the idea of having a 4th canvas layer that is used for previewing the circle before placing. This could help minimise redrawing the canvas each time especially for images with large numbers of labels, such as our rocks.

Could you please clean up the commit history by squashing the commits, since there are quite a few commits with small but related changes? You could then rebase the squashed commits onto current master so that the changes are confined to a few logical steps. 

Let me know if you have any queries.

**Comment by RF5** [comment]
Is this fine? I am not too sure why the travic-ci build is failing though, ot sure if it has to do with the pr or not, but from the log it does not seem like it. If I still need to fix something just say :+1:

**Comment by shaunirwin** [comment]
I think what could be causing the issue is that you have pushed your master branch instead of a feature branch. If I merge this PR as is, it will include the merge commit that you made to merge the feature into your master. Essentially the history on your master would look different to the one in this repo after completing the PR, which is a problem for a repo that is forked from another.

So I think an easy solution is to hard reset your repo to one commit prior, which will then be on a different (feature) branch to master, then push this feature branch rather than the master branch. 

Also, it would be good to rename the commit to something more descriptive before pushing, so that we can easily navigate the git history down the line.

**Comment by shaunirwin** [comment]
You will probably need to push the feature branch, then

**Pull request closed without merging**
